language: cpp
os:
  - linux
  - osx
sudo: required
dist: xenial
compiler:
  - gcc
  - clang
branches:
  only:
  - master
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt5-default qt5-qmake gdb librtaudio-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 180 brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 180 brew install qt5 rt-audio ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$(brew --prefix)/opt/qt5/bin:$PATH ; fi
script:
  - qmake rtaudiostreamer.pro -r CONFIG+=debug
  - make
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make distclean ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "catchTests=false" > globals.pri ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then qmake rtaudiostreamer.pro -r CONFIG+=release ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x pkgs/macOS.sh && pkgs/macOS.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x pkgs/osx/deploy.sh && pkgs/osx/deploy.sh ; fi
